#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
unsetopt CORRECT                      # Disable autocorrect guesses. Happens when typing a wrong
                                      # command that may look like an existing one.

expand-or-complete-with-dots() {      # This bunch of code displays red dots when autocompleting
  echo -n "\e[31m......\e[0m"         # a command with the tab key, "Oh-my-zsh"-style.
  zle expand-or-complete
  zle redisplay
}
zle -N expand-or-complete-with-dots
bindkey "^I" expand-or-complete-with-dots

# History search tweeks
bindkey "^R" history-incremental-search-backward
bindkey -M vicmd '/' history-incremental-search-backward

# Aliases
alias ls="ls --group-directories-first --color=auto"
alias la="ls -A"
alias ll="ls -lAh"
alias df="df -h"
alias du="du -h"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias rgrep="rgrep --color=auto"


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/jbulcher/google-cloud-sdk/path.zsh.inc' ]; then source '/home/jbulcher/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/jbulcher/google-cloud-sdk/completion.zsh.inc' ]; then source '/home/jbulcher/google-cloud-sdk/completion.zsh.inc'; fi

